### ISSUE TITLE
running out of memory

### ISSUE THREAD

**Issue by leolle** [salesforce/decaNLP#15]
I am trying to train a Multitask Question Answering Network (MQAN) on the Stanford Question Answering Dataset (SQuAD).
My GPU has 11GB memory.
I met such error:
```
process_0 - Begin Training
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "/decaNLP/train.py", line 365, in <module>
    main()
  File "/decaNLP/train.py", line 361, in main
    run(args, run_args, world_size=args.world_size)
  File "/decaNLP/train.py", line 309, in run
    writer=writer if rank==0 else None, save_every=args.save_every, start_iteration=start_iteration)
  File "/decaNLP/train.py", line 220, in train
    loss, train_metric_dict = step(model, batch, opt, iteration, field, task, lr=lr, grad_clip=args.grad_clip, writer=writer, it=train_iter)
  File "/decaNLP/train.py", line 130, in step
    loss, predictions = model(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/decaNLP/models/multitask_question_answering_network.py", line 116, in forward
    oov_to_limited_idx)
  File "/decaNLP/models/multitask_question_answering_network.py", line 153, in probs
    p_question_ptr = Variable(scaled_p_vocab.data.new(*scaled_p_vocab.size()).fill_(EPSILON))
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCStorage.cu:58

```
any idea how to fix it?

**Comment by bmccann** [comment]
The easiest way is to try lowering the batch size by setting —train_batch_tokens.

**Comment by leolle** [comment]
@bmccann thank you.
I think the author should put the caveat under the running command just in case somebody meets the same issue as me.
