### ISSUE TITLE
Permission Error when training

### ISSUE THREAD

**Issue by sooheon** [salesforce/decaNLP#7]
I've followed instructions in README, up to the point of training a model on the decathlon.

```
Traceback (most recent call last):
  File "/decaNLP/train.py", line 340, in <module>
    args = arguments.parse()
  File "/decaNLP/arguments.py", line 112, in parse
    save_args(args)
  File "/decaNLP/arguments.py", line 18, in save_args
    os.makedirs(args.log_dir, exist_ok=args.exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 4 more times]
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/runtime'
```

Apparently at some point the code tries to create some directories under `/runtime` without having the right permissions. I tried running the whole command with `sudo`, tinkering with setting `os.umask()` in the `save_args` code, but I'm not familiar with permissions and docker-nvidia. 

Any pointers as to how to avoid permissions issues while running this code?

**Comment by bmccann** [comment]
Thanks for catching this. I believe it is because I left 'runtime' in some places instead of uniformly renaming to 'decaNLP'. fbf94815c8a03cc1602106e7656868ba2cb8058b should take care of this, but let me know if you still have this issue.

**Comment by BlackRedGold** [comment]
I also had this problem: "PermissionError: [Errno 13] Permission denied: '/runtime'"
I removed "-u $(id -u):$(id -g)" from the "nvidia-docker run ..." and problem disappeared.
But I doubt that this is a good solution.

**Comment by bmccann** [comment]
That’s a fine solution if you’re okay running as root within the docket container. Did you run into this even after the commit from my last comment?
